### ISSUE TITLE
Extend Australian Securities Exchange (XASX) Holidays

### ISSUE THREAD

**Issue by RichardDale** [quantopian/trading_calendars#100]
Australian holidays are only accurate back to 2010.  This PR will extend the Australian Securities Exchange holiday calendar back to 1992.

**Comment by savvyyabby** [comment]
See my pull request. Fills in XASX holidays back to Jan-1973

**Comment by gerrymanoim** [comment]
Link to the relevant PR: https://github.com/quantopian/trading_calendars/pull/101

**Comment by jmccorriston** [comment]
Closing this since #101 was merged. Thanks again, @savvyyabby!
