### ISSUE TITLE
Need help on how to use the trading calender

### ISSUE THREAD

**Issue by grsb007** [quantopian/trading_calendars#106]
Hello Team,

I am new to python and wanted to know how to use the trading XBOM calendar, for example 

today =  datetime.date.today() i.e. 25th Dec 2019. how to check this date is in holiday list or not with condition 

And also given time in market hours are not can someone help with sample code

**Comment by gerrymanoim** [comment]
Hey @grsb007, thank you for pointing this out. The code for grabbing calendars can be seen at https://github.com/quantopian/trading_calendars#usage. For your specific question, you could do something like (substituting your desired calendar as appropriate):

```
from trading_calendars import get_calendar
nyse = get_calendar("NYSE")
nyse.is_session("2019-12-31")
>> True
nyse.is_session("2020-01-01")
>> False
```

I've added https://github.com/quantopian/trading_calendars/issues/107 for us to go through and better document this.

**Comment by grsb007** [comment]
Hello @Gerrymanoim, Thanks a lot for providing the sample. It is very useful and thanks for adding this to documentation. Btw once again it is very useful it saves me lot of time
