### ISSUE TITLE
Is coveralls really used?

### ISSUE THREAD

**Issue by willianpaixao** [quantopian/trading_calendars#111]
In `.travis.yml`, coveralls is installed and runs in the end of the pipeline:

https://github.com/quantopian/trading_calendars/blob/e7a64fc5c7aca83e1e67dc358076fa1a94a6e94a/.travis.yml#L24

but apparently the project is not created in the Coveralls website [[1]](https://coveralls.io/r/quantopian/trading_calendars), basically discarding any report sent. Am I right?

**Comment by gerrymanoim** [comment]
Yep - good catch. 

Removing in https://github.com/quantopian/trading_calendars/pull/114.
