### ISSUE TITLE
Add tests_require to setup.py

### ISSUE THREAD

**Issue by leonarduschen** [quantopian/trading_calendars#143]
This is a follow up to #113 

Setting up the required packages to run the tests for the first time was a hassle for me. It's probably a good idea to add test dependencies to setup.py to make it easier for us to contribute.

Dependencies:
`nose`
`nose-ignore-docstring`
`nose-timer`
`nose-parameterized`

**Comment by gerrymanoim** [comment]
Currently we install from the requirements file at https://github.com/quantopian/trading_calendars/blob/master/etc/requirements.txt (for example, the command in testing is here: https://github.com/quantopian/trading_calendars/blob/master/.github/workflows/main.yml#L42). 

I agree that this should also live in an `extras_require` under `test`.
