### ISSUE TITLE
Minor failures in all calendar tests

### ISSUE THREAD

**Issue by leonarduschen** [quantopian/trading_calendars#145]
As the title suggests, there is always a minor failures in all calendar test `tests\test_XXXX_calendar.py` for all exchange code XXXX

For example, running `nosetests tests\test_xnys_calendar.py` yields

```
[success] 49.38% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minute_to_session_label: 7.4921s
[success] 12.18% tests.test_xnys_calendar.XNYSCalendarTestCase.test_open_and_close_for_session: 1.8481s
[success] 11.56% tests.test_xnys_calendar.XNYSCalendarTestCase.test_next_prev_open_close: 1.7531s
[success] 11.36% tests.test_xnys_calendar.XNYSCalendarTestCase.test_next_prev_minute: 1.7233s
[success] 3.56% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minute_index_to_session_labels_0: 0.5395s
[success] 3.05% tests.test_xnys_calendar.XNYSCalendarTestCase.test_next_prev_session: 0.4620s
[success] 2.26% tests.test_xnys_calendar.XNYSCalendarTestCase.test_sanity_check_session_lengths: 0.3434s
[success] 1.79% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minute_index_to_session_labels_2: 0.2719s
[success] 1.78% tests.test_xnys_calendar.XNYSCalendarTestCase.test_is_open_on_minute: 0.2705s
[success] 1.73% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minute_index_to_session_labels_1: 0.2623s
[success] 0.94% tests.test_xnys_calendar.XNYSCalendarTestCase.test_start_end: 0.1422s
[fail] 0.12% tests.test_xnys_calendar.XNYSCalendarTestCase.test_session_closes_in_range: 0.0187s
[success] 0.06% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minutes_for_period: 0.0096s
[fail] 0.05% tests.test_xnys_calendar.XNYSCalendarTestCase.test_session_opens_in_range: 0.0069s
[success] 0.04% tests.test_xnys_calendar.XNYSCalendarTestCase.test_minutes_in_range: 0.0054s

Ran 27 tests in 15.773s

FAILED (failures=2)
```

**Comment by gerrymanoim** [comment]
It is weird that you're experiencing failures in tests. Our CI runs tests on pandas 0.18.1 (what quantopian.com uses) and 1.0.1 https://github.com/quantopian/trading_calendars/blob/master/.github/workflows/main.yml#L16, and I don't see any failures in either (for example looking at the CI from your changes here: https://github.com/quantopian/trading_calendars/runs/1052679766?check_suite_focus=true).

**Comment by gerrymanoim** [comment]
Were you running this with pandas 1.1.1?

**Comment by leonarduschen** [comment]
> Were you running this with pandas 1.1.1?

Turns out I was! My apologies for the false alarm.

After some digging, it turns out pandas changed `assert_series_equal` default behavior somewhere between 1.0.1 and 1.1.1 to check for frequency.

**Comment by gerrymanoim** [comment]
No problem - I've pulled your changes into my branch updating the tests and will merge them there. Thanks!
