### ISSUE TITLE
Exclude business day every week from the calendar

### ISSUE THREAD

**Issue by ogenev** [quantopian/trading_calendars#167]
Hello, I'm trying to exclude a business day, any week, from a trading calendar.

Lets say I don't want to trade on any Friday, what I'm doing is changing the weekmask:

    class CustomCalendar(IEPAExchangeCalendar):
        def __init__(self):
            super().__init__()

        @property
        def weekmask(self):
           return '111000'

    custom_calendar = CustomCalendar()

but I'm getting:

`ValueError: Special dates [Timestamp('1992-07-03 17:00:00+0000', tz='UTC'), ..., ...] are not trading days.`

What is the best way to exclude business day every week?

**Comment by gerrymanoim** [comment]
Can you provide more detail on where you are getting that error?

**Comment by ogenev** [comment]
> Can you provide more detail on where you are getting that error?

Sure, my bad:

     File "/home/dev/venv/lib/python3.8/site-packages/trading_calendars/trading_calendar.py", line 131, in __init__
    _overwrite_special_dates(_all_days, self._closes, _special_closes)
     File "/home/dev/venv/lib/python3.8/site-packages/trading_calendars/trading_calendar.py", line 1045, in _overwrite_special_dates

    raise ValueError("Special dates %s are not trading days." % bad_dates)
    ValueError: Special dates [Timestamp('1992-07-03 17:00:00+0000', tz='UTC'), Timestamp('1997-07-04 17:00:00+0000', tz='UTC'), Timestamp('1998-07-03 17:00:00+0000', tz='UTC'), Timestamp('2003-07-04 17:00:00+0000', tz='UTC'), Timestamp('2008-07-0417:00:00+0000', tz='UTC'), Timestamp('2009-07-03 17:00:00+0000', tz='UTC'), Timestamp('2014-07-04 17:00:00+0000', tz='UTC'), Timestamp('2015-07-03 17:00:00+0000', tz='UTC'), Timestamp('2020-07-03 17:00:00+0000', tz='UTC')] are not trading days.
`

**Comment by gerrymanoim** [comment]
The reason you're having that issue is `IEPAExchangeCalendar` defines special closes (https://github.com/quantopian/trading_calendars/blob/58559401096b7c5fb86ea610bb495ac6b7b6d01c/trading_calendars/exchange_calendar_iepa.py#L51) but with your week mask, those special closes aren't in the list of trading days, so when we try to apply early closes to them, we get a bad index error (you can't have a holiday and an early close on the same day). 

To clarify - you want `IEPAExchangeCalendar` with the existing schedule, but also closures on specific days?

**Comment by ogenev** [comment]
> To clarify - you want `IEPAExchangeCalendar` with the existing schedule, but also closures on specific days?

Yes, I just don't want to trade on Friday. I tried to add a custom pandas Holiday, but I had no success by defining holiday every week, on Friday.

**Comment by gerrymanoim** [comment]
I think your easiest bet is to handle that outside of trading calendars. Depending on how you're using it, checking the weekday before you put a date in or after you get a day out. 

The other option is to override `special_closes` to be `[]` if you don't care about the closing times, or create version of the holidays already in there that don't occur on Friday.

**Comment by ogenev** [comment]
Thank you very much! I will try to play with it.
