### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by gitcnd** [quantopian/trading_calendars#178]
This is helpful:-

us_calendar = get_calendar('XNYS')

But there's no doc about what us_calendar is, or what can be done with it?  (if anything?)

I get that this is for Zipline, but I assume since it's been separated from that codebase, that there's probably a way to use it stand-alone?  If yes, I'd love some hints/clues/pointers for that - thanks!!

**Comment by gerrymanoim** [comment]
There's an in progress PR for documentation here: https://github.com/quantopian/trading_calendars/pull/177. 

We have a plan for more detailed documentation in the future, but haven't had a chance to make it yet.
