### ISSUE TITLE
Can we have tz-naive calendars?

### ISSUE THREAD

**Issue by yangrq1018** [quantopian/trading_calendars#193]
The `TradingCalendar` Class is heavily reliant on UTC timezone, this makes it really awkward to compare the dates with tz-naive datetime objects,  which I believe is a common case in developing small applications that target only a single country's exchange. Is such time-awareness an overkill? Could there be a non-tz-aware calendar class?

**Comment by teathinker** [comment]
You can use pytz to convert though, which could be easier than a local time class.

**Comment by yangrq1018** [comment]
@teathinker yes that's possible certainly. I was doing things like that before (basically wrapping every method I need with a `tz_localize(None)`), that's why I feed this is kind of tiresome. Ideally, the user could set the `tz` attribute to None and get a naive subclass, currently that's not possible
