### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Hammy27** [quantopian/trading_calendars#203]
When using this code:

```
import trading_calendars as tc
exchange = tc.get_calendar('XSWX')
exchange.next_open(pd.Timestamp('2021-12-27')
```

an index 8032 is out of bounds error for axis 0 with size 8032 is thrown.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\raphael\anaconda3\envs\levine\lib\site-packages\trading_calendars\trading_calendar.py", line 462, in next_open
    idx = next_divider_idx(self.market_opens_nanos, dt.value)
  File "C:\Users\raphael\anaconda3\envs\levine\lib\site-packages\trading_calendars\calendar_helpers.py", line 12, in next_divider_idx
    target = dividers[divider_idx]
IndexError: index 8032 is out of bounds for axis 0 with size 8032
```

Seems to be a pandas Problem?

**Comment by gerrymanoim** [comment]
This is an artifact of https://github.com/quantopian/trading_calendars/blob/master/trading_calendars/trading_calendar.py#L47. 

You can get around this via https://github.com/quantopian/trading_calendars/issues/147. 

There was some discussion about making this process smoother via https://github.com/quantopian/trading_calendars/pull/176.  

I think in the next year I'll work on some backwards incompatible features and put this enhancement in under a new version.
