### ISSUE TITLE
Import of Library fails

### ISSUE THREAD

**Issue by metin-akyol** [quantopian/trading_calendars#249]
Running a simple import on Win 10 machine:

import trading_calendars as tc

produces this error:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

**Comment by rsheftel** [comment]
This package is not longer maintained. Read here:

https://github.com/quantopian/trading_calendars#important-note

**Comment by metin-akyol** [comment]
Oh I didn't realize, thank you! In case any one else has the same issue, I switched to Pandas market calendar.
