### ISSUE TITLE
Syntax error on python 3.5.2 and python 2.7

### ISSUE THREAD

**Issue by sjerry4u** [quantopian/trading_calendars#28]
Hello,
I ran `python etc/lunisolar lunar-ecliptic-longitude --verbose --start '2005-01-01'` with python 3.5.2 and 2.7 in virtual envs. Its throwing and syntax error. It is running fine with 3.6.6 though.
```
  File "etc/lunisolar", line 186
    return np.datetime64(f'{year}-{month:02d}-{day:02d}', 'D')
```
My default python is 3.6.6, but I had to install Python 3.5 because I could not get Zipline running on 3.6. Script etc/lunisolar and Zipline are in incompatible environments.

Thanks

**Comment by llllllllll** [comment]
This script does not run, nor is installed, as part of the normal operation of the trading calendars project so it currently only supports 3.6.
