### ISSUE TITLE
end_default trading days limited to one year out

### ISSUE THREAD

**Issue by bdowling** [quantopian/trading_calendars#36]
I didn't get a chance to dig into why this is happening, but thought I'd mention it.  Hopefully this isn't predicting the end of the world!  pd.date_range() responds as expected for these inputs, so I think it's a local issue not upstream, but didn't dig too far.

I have hope there is plenty of time for us to fix the future!

```python
from trading_calendars import get_calendar

# US Stock Exchanges (includes NASDAQ)
XNYS_calendar = get_calendar('XNYS')

print("Last month is 2019-10:")
print( XNYS_calendar.sessions_in_range("2019-10", "2020") )

print("2019-11 and beyond:")
print( XNYS_calendar.sessions_in_range("2019-11", "2020") )

```

### Results:
```
Last month is 2019-10:
DatetimeIndex(['2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
               '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10',
               '2019-10-11', '2019-10-14', '2019-10-15', '2019-10-16',
               '2019-10-17', '2019-10-18', '2019-10-21', '2019-10-22',
               '2019-10-23', '2019-10-24', '2019-10-25', '2019-10-28',
               '2019-10-29', '2019-10-30'],
              dtype='datetime64[ns, UTC]', freq='C')

2019-11 and beyond:
DatetimeIndex([], dtype='datetime64[ns, UTC]', freq='C')

```

**Comment by bdowling** [comment]
Ok, so I glanced at the calendar and realized something must be limiting the range to one year out, proved using faketime below..  So it's not a flaw, but a limitation somewhere that doesn't jump out grep'ing the code.  Likely related to #37 that was just coincidentally was posted.

```
$ faketime -f +5d ./marketdays-inrange.py -a --start 2019-10-28 --end 2020
2019-10-28
2019-10-29
2019-10-30
2019-10-31
2019-11-01
2019-11-04
```

**Comment by jmccorriston** [comment]
@bdowling thanks for filing this issue, and sorry for taking so long to reply. I think it would be nice if one could specify/override the `start` and `end` of the calendar via `get_calendar`. I don't know when we will get a chance to add the feature, but I'm leaving the issue open and adding the 'enhancement' label.

**Comment by gerrymanoim** [comment]
Closing in favor of https://github.com/quantopian/trading_calendars/issues/147, where I'm consolidating these issues.
