### ISSUE TITLE
Add trading_calendars to Quantopian conda channel

### ISSUE THREAD

**Issue by ttt733** [quantopian/trading_calendars#40]
Hello, I am working on building a conda package for our library, and it uses trading_calendars. I'm having a hard time building my own version of the conda package for trading_calendars due to some odd dependency issues. Do you have any plans to add this project to Quantopian's conda channel? I'm hoping that you'll be able to avoid some of the issues I was running into and that I'll just be able to pull your package when it's on there.

**Comment by ssanderson** [comment]
@ttt733 we've actually had trading-calendars on the conda channel for a while, but we hadn't promoted any builds from our `ci` label to `main` (we build all our conda packages as part of the zipline build, so the `ci` builds get pushed once the zipline test suite passes with a newly-released version of this repo). I've just gone through and promoted releases for 1.2, 1.3.1, 1.4.2, and 1.5.1.

**Comment by ttt733** [comment]
Oh, you know what, I just wasn't seeing it because I was searching with the _ instead of the -. But thank you for updating it!
