### ISSUE TITLE
Create a version of prevous_session_label that takes any date, not just sessions

### ISSUE THREAD

**Issue by gmanoim-quantopian** [quantopian/trading_calendars#46]
`previous_session_label` requires that the date you pass actually be a session. 

We should have an equivalent that takes any date and a calendar and passes back the session occurring prior to that date. Vague pseudo-code:

```python
def last_valid_session(dt, exch='NYSE'):    
    cal = tc.get_calendar(exch)
    if cal.is_session(date):
        return cal.previous_session_label(dt)
    else:
        while not cal.is_session(dt):
            dt = dt-1
        return dt
```

**Comment by ssanderson** [comment]
@gmanoim-quantopian it sounds like you might want some variation of `minute_to_session_label`?

The behavior of that function is, essentially "if the input minute is during market hours, return the session containing that minute". Otherwise, roll to the next/previous market minute (depending on `direction`), and take the corresponding session.

So, for example:

`direction='next'`

```
In [22]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07', tz='US/Eastern'), direction='next')
Out[22]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')

In [23]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 9:15', tz='US/Eastern'), direction='next')
Out[23]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')

In [24]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 9:45', tz='US/Eastern'), direction='next')
Out[24]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')

In [25]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 16:00', tz='US/Eastern'), direction='next')
Out[25]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')

In [26]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 16:01', tz='US/Eastern'), direction='next')
Out[26]: Timestamp('2019-02-08 00:00:00+0000', tz='UTC', offset='C')
```

`direction='next'`

```
In [5]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 9:25', tz='US/Eastern'), direction='previous')
Out[5]: Timestamp('2019-02-06 00:00:00+0000', tz='UTC', offset='C')

In [6]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 9:35', tz='US/Eastern'), direction='previous')
Out[6]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')

In [7]: nyse.minute_to_session_label(pd.Timestamp('2019-02-07 16:05', tz='US/Eastern'), direction='previous')
Out[7]: Timestamp('2019-02-07 00:00:00+0000', tz='UTC', offset='C')
```

The main reason why `last_valid_session` doesn't exist as you're describing it is that there aren't very many contexts where you want to convert an intraday value to a session label, and where utc-midnight (aka 8:00pm eastern) is the right boundary, especially not for an arbitrary calendar. Most of the time the right boundary is market open, market close, or midnight in the timezone of the calendar.

**Comment by gmanoim-quantopian** [comment]
Yep - basically exact that, but maybe even with a different name? It just isn't clear to me off the bat that I should use that. 

This came up in the context where I knew that the date I had wasn't a trading day (Sunday in the US), but I wanted to find what the previous NYSE trading day was.

**Comment by ssanderson** [comment]
Ah, I understand now. When you wrote "`previous_session_label` requires that the date you pass actually be a session.", I assumed that the non-session values you had were intraday minutes, as opposed to midnight UTCs for non-trading days.

If you know you already have a "date", the easiest way to do what you want is probably to use `calendar.day`:

```
# This coming saturday
In [15]: pd.Timestamp('2019-02-09', tz='UTC') - nyse.day
Out[15]: Timestamp('2019-02-08 00:00:00+0000', tz='UTC')

In [16]: pd.Timestamp('2019-02-09', tz='UTC') + nyse.day
Out[16]: Timestamp('2019-02-11 00:00:00+0000', tz='UTC')
```

I'd also be less worried about making `{next,previous}_session_label` work in cases like this, where the value you've passed is a "date" that's not necessarily a market date.

**Comment by gmanoim-quantopian** [comment]
That's perfect actually, just unexpected for me (as a first time user). I'm not quite sure what I would expect `+`/`-` to do, but I wouldn't expect it to go to next/previous. Thanks!
