### ISSUE TITLE
Is it possible to make a break in a calendar?

### ISSUE THREAD

**Issue by bbqaaq** [quantopian/trading_calendars#54]
Hi,

Currently Im trying to make a own custom calendar, which needs to have multiple break in a single trading day.

So far as I drilled the source code, seems the current calendar implementation dont support a break during a single trading day, as each day can only have a record in the 'schedule' variable with a single 'market_open' and 'market_close'.

So may I ask if there is any idea on how to implement this? or any other approaches I can do?

**Comment by jbredeche** [comment]
Hi @bbqaaq, thanks for your question.  Unfortunately, right now intraday breaks aren't supported - if and when we get to modeling the Japanese market, with its daily lunch break, we'll have to figure this out.  As you said, right now a trading session is defined as a contiguous amount of time between an open and its immediately following close.

We'd probably need to layer in the notion of daily breaks, maybe as an offset from the open and the close, or in absolute times.  The API would also have to let you define how those daily breaks interact with short sessions (early closes or late opens).

**Comment by bbqaaq** [comment]
Thanks you so much for your reply.

Indeed our side is doing something about HK's future market. I have spent quite a lot of time investigating the XHKG calendar as a reference, and found that the lunch time actually not working.

For HK future's market calendar I guess it would be even more troublesome, as there are actually multiple breaks in each day(a lunch break, and break between day trade market and night trade market).

**Comment by bbqaaq** [comment]
And sorry for sidetracking the topic, another big challenge for me to implement the HK futures' calendar is that the time schedule change quite a few times in the past few years, esp. in Nov 2017 the night shift market close time was changed from 11:45pm to 1:00am on the next day.

The difficulty comes as the `close_offset` needs to be changed from 0 to +1, however seems the offset is a single constant which cannot be vary according to time. This will cause the calendar unable to handle properly before Nov 2017 as the day offset has changed according to the close time change (+1). And so far I cannot find the solution for this.

**Comment by gerrymanoim** [comment]
You could check https://github.com/quantopian/trading_calendars/pull/98/files for an example where the close times changed over time. 

https://github.com/pandas-dev/pandas/issues/15481 was added to pandas 0.25, but we haven't gotten around to updating trading calendars for this new version yet.
