### ISSUE TITLE
MAINT: Fix tests on Travis

### ISSUE THREAD

**Issue by gmanoim-quantopian** [quantopian/trading_calendars#58]
Builds with 
Python: 3.5, PANDAS_VERSION=0.18.1 NUMPY_VERSION=1.11.3
fail on travis (linux 64) because conda is unable to resolve dependencies. 

https://travis-ci.org/quantopian/trading_calendars/jobs/554823104

**Comment by willianpaixao** [comment]
@richafrank I guess this issue can be closed.

**Comment by richafrank** [comment]
Ah, thanks!
